version: "3"

services:
  db:
    restart: always
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_image_db
  web:
    restart: always
    build: ./web
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - db
